load("@package_metadata//purl:purl.bzl", "purl")
load("@package_metadata//rules:package_metadata.bzl", "package_metadata")
load("@rules_license//rules:license.bzl", "license")

package(
    default_visibility = ["//visibility:public"],
)

license(
    name = "license",
    license_kinds = ["@rules_license//licenses/spdx:MIT"],
    license_text = "LICENSE",
)

package_metadata(
    name = "package_metadata",
    purl = purl.bazel(
        module_name(),
        module_version(),
    ),
    visibility = ["//visibility:public"],
)

exports_files(
    [
        "defs.bzl",
        "toolchains.bzl",
    ],
)

toolchain_type(
    name = "xslt_toolchain_type",
)
