package(default_visibility = ["//visibility:public"])

exports_files([
    "LIB_WORDML_CONTENT_CONTROLS.xslt",
    "LIB_WORDML_DOCUMENT.xslt",
    "LIB_WORDML_STYLES.xslt",
    "LIB_WORDML_TABLES.xslt",
    "LIB_WORDML_TEXT.xslt",
    "MERGE_TO_TEMPLATE.xslt",
])

filegroup(
    name = "libxslt",
    srcs = [
        "LIB_WORDML_CONTENT_CONTROLS.xslt",
        "LIB_WORDML_DOCUMENT.xslt",
        "LIB_WORDML_STYLES.xslt",
        "LIB_WORDML_TABLES.xslt",
        "LIB_WORDML_TEXT.xslt",
        "MERGE_TO_TEMPLATE.xslt",
    ],
)

filegroup(
    name = "append_template_transform",
    srcs = ["MERGE_TO_TEMPLATE.xslt"],
)
